version: '3.6'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=test'
      - 'MYSQL_USER=test'
      - 'MYSQL_PASSWORD=test'
    ports:
      - '127.0.0.1:3306:3306'

volumes:
  mysql_data:
